export const key = {
  ACF: 'Administration for Children and Families',
  AMS: 'Agricultural Marketing Service',
  ATF: 'Bureau of Alcohol, Tobacco, Firearms and Explosives',
  BEA: 'Bureau of Economic Analysis',
  BEP: 'Bureau of Engraving and Printing',
  BIS: 'Bureau of Industry and Security',
  BLM: 'Bureau of Land Management',
  BOP: 'Bureau of Prisons',
  CDC: 'Centers for Disease Control and Prevention',
  CMS: 'Centers for Medicare and Medicaid Services',
  CIA: 'Central Intelligence Agency',
  CBO: 'Congressional Budget Office',
  DIA: 'Defense Intelligence Agency',
  DLA: 'Defense Logistics Agency',
  DOC: 'Department of Commerce',
  DOD: 'Department of Defense',
  DOE: 'Department of Energy',
  HHS: 'Department of Health and Human Services',
  DHS: 'Department of Homeland Security',
  HUD: 'Department of Housing and Urban Development',
  DOJ: 'Department of Justice',
  DOL: 'Department of Labor',
  DOS: 'Department of State',
  DOI: 'Department of the Interior',
  DOT: 'Department of Transportation',
  DEA: 'Drug Enforcement Administration',
  EDA: 'Economic Development Administration',
  EAC: 'Election Assistance Commission',
  EPA: 'Environmental Protection Agency',
  FAA: 'Federal Aviation Administration',
  FBI: 'Federal Bureau of Investigation',
  FCC: 'Federal Communications Commission',
  FHA: 'Federal Housing Administration',
  FRA: 'Federal Railroad Administration',
  FTC: 'Federal Trade Commission',
  FTA: 'Federal Transit Administration',
  FWS: 'Fish and Wildlife Service',
  FDA: 'Food and Drug Administration',
  GSA: 'General Services Administration',
  GAO: 'Government Accountability Office',
  GPO: 'Government Publishing Office',
  ICE: 'Immigration and Customs Enforcement',
  IAQ: 'Indoor Air Quality',
  IRS: 'Internal Revenue Service',
  DFC: 'International Development Finance Corporation',
  ITA: 'International Trade Administration',
  LOC: 'Library of Congress',
  MDA: 'Missile Defense Agency',
  NCI: 'National Cancer Institute',
  NEA: 'National Endowment for the Arts',
  NIH: 'National Institutes of Health',
  NPS: 'National Park Service',
  NSF: 'National Science Foundation',
  NSA: 'National Security Agency',
  NSC: 'National Security Council',
  NRC: 'Nuclear Regulatory Commission',
  OGE: 'Office of Government Ethics',
  IER: 'Office of Immigrant and Employee Rights',
  OMB: 'Office of Management and Budget',
  OPM: 'Office of Personnel Management',
  OCC: 'Office of the Comptroller of the Currency',
  OVW: 'Office on Violence Against Women',
  RFA: 'Radio Free Asia',
  RFE: 'Radio Free Europe',
  RRB: 'Railroad Retirement Board',
  SEC: 'Securities and Exchange Commission',
  SSS: 'Selective Service System',
  SBA: 'Small Business Administration',
  SSA: 'Social Security Administration',
  TVA: 'Tennessee Valley Authority',
  TSA: 'Transportation Security Administration',
  VBA: 'Veterans Benefits Administration',
  VHA: 'Veterans Health Administration',
  VOA: 'Voice of America',
  WHD: 'Wage and Hour Division',
}
